replicaCount: 2

image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/devops-portfolio
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: devops-portfolio.example.com
      paths:
        - path: /
          pathType: Prefix
